export const RECEIVE_TOKEN = "RECEIVE_TOKEN";
export const REQUEST_TOKEN = "REQUEST_TOKEN";
export const REQUEST_TOKEN_FAIL = "REQUEST_TOKEN_FAIL";

export const AUTH_BEGIN = "AUTH_BEGIN";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";

export const DEAUTH_BEGIN = "DEAUTH_BEGIN";
export const DEAUTH_SUCCESS = "DEAUTH_SUCCESS";
export const DEAUTH_FAILURE = "DEAUTH_FAILURE";

export const SEND_BEGIN = "SEND_BEGIN";
export const SEND_SUCCESS = "SEND_SUCCESS";
export const SEND_FAILURE = "SEND_FAILURE";

export const LOAD_BEGIN = "LOAD_BEGIN";
export const LOAD_SUCCESS = "LOAD_SUCCESS";
export const LOAD_FAILURE = "LOAD_FAILURE";
