export const OPEN_SIDE_NAV = "OPEN_SIDE_NAV";
export const CLOSE_SIDE_NAV = "CLOSE_SIDE_NAV";

export const RECEIVE_TOKEN = "RECEIVE_TOKEN";
export const REQUEST_TOKEN = "REQUEST_TOKEN";
export const REQUEST_TOKEN_FAIL = "REQUEST_TOKEN_FAIL";

export const AUTH_BEGIN = "AUTH_BEGIN";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";

export const DE_AUTH_BEGIN = "DE_AUTH_BEGIN";
export const DE_AUTH_SUCCESS = "DE_AUTH_SUCCESS";
export const DE_AUTH_FAILURE = "DE_AUTH_FAILURE";

export const CREATE_CHAT_MESSAGE_BEGIN = "CREATE_CHAT_MESSAGE_BEGIN";
export const CREATE_CHAT_MESSAGE_SUCCESS = "CREATE_CHAT_MESSAGE_SUCCESS";
export const CREATE_CHAT_MESSAGE_FAILURE = "CREATE_CHAT_MESSAGE_FAILURE";

export const CREATE_CHAT_BEGIN = "CREATE_CHAT_BEGIN";
export const CREATE_CHAT_SUCCESS = "CREATE_CHAT_SUCCESS";
export const CREATE_CHAT_FAILURE = "CREATE_CHAT_FAILURE";

export const LOAD_CHATS_BEGIN = "LOAD_CHATS_BEGIN";
export const LOAD_CHATS_SUCCESS = "LOAD_CHATS_SUCCESS";
export const LOAD_CHATS_FAILURE = "LOAD_CHATS_FAILURE";

export const LOAD_CHAT_MESSAGES_BEGIN = "LOAD_CHAT_MESSAGES_BEGIN";
export const LOAD_CHAT_MESSAGES_SUCCESS = "LOAD_CHAT_MESSAGES_SUCCESS";
export const LOAD_CHAT_MESSAGES_FAILURE = "LOAD_CHAT_MESSAGES_FAILURE";

export const SET_CURRENT_CHAT = "SET_CURRENT_CHAT";

export const CLEAR_CHAT_MESSAGES_LIST = "CLEAR_CHAT_MESSAGES_LIST";

export const SELECT_CHAT_BEGIN = 'SELECT_CHAT_BEGIN';
export const SELECT_CHAT_SUCCESS = 'SELECT_CHAT_SUCCESS';
export const SELECT_CHAT_FAILURE = 'SELECT_CHAT_FAILURE';