# Generated by Django 2.0.1 on 2019-01-02 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flood_app', '0002_chat_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_order', models.PositiveIntegerField(default=1)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flood_app.Chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-user', '-force_order', '-chat'),
            },
        ),
        migrations.RemoveField(
            model_name='message',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AlterUniqueTogether(
            name='access',
            unique_together={('user', 'chat')},
        ),
    ]
