# Generated by Django 2.0.1 on 2019-01-02 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flood_app', '0003_auto_20190102_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'ordering': ('-user', '-rank_order', '-chat')},
        ),
        migrations.RenameField(
            model_name='access',
            old_name='force_order',
            new_name='rank_order',
        ),
    ]
